language: python
python: 3.7
addons:
  apt:
    packages:
    - bash
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- pytest -v --cov=emlearn --cov-report html --cov-report term-missing --cov-branch
